import { Category } from './types';

export const categories: Category[] = [
  {
    id: 'nauka-i-ucheba',
    slug: 'nauka-i-ucheba',
    title: 'Наука и Учёба',
    description: 'Математические калькуляторы, проценты, дроби, геометрия и физика',
    subcategories: [
      { id: 'matematicheskie', slug: 'matematicheskie', title: 'Математические', description: 'Базовые и инженерные калькуляторы' },
      { id: 'finansovye', slug: 'finansovye', title: 'Финансовые', description: 'Проценты, кредиты, налоги' },
      { id: 'geometriya', slug: 'geometriya', title: 'Геометрия', description: 'Площади, объёмы, фигуры' },
      { id: 'fizika', slug: 'fizika', title: 'Физика', description: 'Физические расчёты и законы' },
    ],
  },
  {
    id: 'konvertery',
    slug: 'konvertery',
    title: 'Конвертеры',
    description: 'Единицы измерения, валюты, температура и многое другое',
    subcategories: [
      { id: 'conv-dlina', slug: 'conv-dlina', title: 'Длина', description: 'Метры, километры, мили, дюймы' },
      { id: 'conv-massa', slug: 'conv-massa', title: 'Масса', description: 'Граммы, килограммы, тонны, фунты' },
      { id: 'conv-temperatura', slug: 'conv-temperatura', title: 'Температура', description: 'Цельсий, Фаренгейт, Кельвин' },
      { id: 'conv-skorost', slug: 'conv-skorost', title: 'Скорость', description: 'км/ч, м/с, узлы, махи' },
      { id: 'conv-informaciya', slug: 'conv-informaciya', title: 'Информация', description: 'Биты, байты, килобайты, мегабайты' },
      { id: 'conv-obem', slug: 'conv-obem', title: 'Объём', description: 'Литры, галлоны, баррели' },
      { id: 'conv-ploshchad', slug: 'conv-ploshchad', title: 'Площадь', description: 'м², гектары, акры, сотки' },
      { id: 'conv-energiya', slug: 'conv-energiya', title: 'Энергия', description: 'Джоули, калории, кВтч' },
      { id: 'conv-davlenie', slug: 'conv-davlenie', title: 'Давление', description: 'Паскали, атм, бар, psi' },
      { id: 'conv-moshchnost', slug: 'conv-moshchnost', title: 'Мощность', description: 'Ватты, киловатты, л.с.' },
      { id: 'conv-vremya', slug: 'conv-vremya', title: 'Время', description: 'Секунды, минуты, часы, дни' },
      { id: 'conv-ugly', slug: 'conv-ugly', title: 'Углы', description: 'Градусы, радианы, грады' },
    ],
  },
  {
    id: 'procenty',
    slug: 'procenty',
    title: 'Проценты',
    description: 'Онлайн калькуляторы процентов для всех типов расчётов',
    subcategories: [
      { id: 'procenty-osnovnye', slug: 'procenty-osnovnye', title: 'Основные расчёты', description: 'Процент от числа, число в процентах' },
      { id: 'procenty-izmenenie', slug: 'procenty-izmenenie', title: 'Изменения', description: 'Прибавить, вычесть процент' },
      { id: 'procenty-slozhnye', slug: 'procenty-slozhnye', title: 'Сложные проценты', description: 'Капитализация, рост' },
    ],
  },
  {
    id: 'tajmery',
    slug: 'tajmery',
    title: 'Таймеры',
    description: 'Онлайн таймеры обратного отсчёта с звуковым сигналом',
    subcategories: [
      { id: 'tajmery-korotkie', slug: 'tajmery-korotkie', title: 'Короткие', description: '5-45 секунд' },
      { id: 'tajmery-minuty', slug: 'tajmery-minuty', title: 'Минуты', description: '1-30 минут' },
      { id: 'tajmery-chasy', slug: 'tajmery-chasy', title: 'Часы', description: '1-24 часа' },
    ],
  },
  {
    id: 'kulinarnye-mery',
    slug: 'kulinarnye-mery',
    title: 'Кулинарные меры',
    description: 'Таблицы перевода кулинарных мер в граммы для всех продуктов',
    subcategories: [
      { id: 'muka', slug: 'muka', title: 'Мука', description: 'Пшеничная, ржаная и другие виды муки' },
      { id: 'krupy', slug: 'krupy', title: 'Крупы', description: 'Рис, гречка, овсянка, манка' },
      { id: 'sahar', slug: 'sahar', title: 'Сахар и сладости', description: 'Сахар, мёд, варенье' },
      { id: 'masla', slug: 'masla', title: 'Масла и жиры', description: 'Сливочное, растительное масло' },
      { id: 'molochnye', slug: 'molochnye', title: 'Молочные продукты', description: 'Молоко, сметана, кефир' },
      { id: 'specii', slug: 'specii', title: 'Приправы', description: 'Соль, сода, специи' },
    ],
  },
  {
    id: 'zdorove-i-krasota',
    slug: 'zdorove-i-krasota',
    title: 'Здоровье и Красота',
    description: 'ИМТ, калории, беременность, фитнес и многое другое',
    subcategories: [
      { id: 'pitanie-i-ves', slug: 'pitanie-i-ves', title: 'Питание и вес', description: 'ИМТ, калории, идеальный вес' },
      { id: 'sport-i-aktivnost', slug: 'sport-i-aktivnost', title: 'Спорт и активность', description: 'Пульс, калории, тренировки' },
      { id: 'beremennost-i-deti', slug: 'beremennost-i-deti', title: 'Беременность и дети', description: 'Овуляция, сроки, календари' },
      { id: 'zdorove-raznoe', slug: 'zdorove-raznoe', title: 'Здоровье (разное)', description: 'Индексы, анализы, нормы' },
      { id: 'vneshnost', slug: 'vneshnost', title: 'Внешность', description: 'Размеры, пропорции, фигура' },
      { id: 'krasota', slug: 'krasota', title: 'Красота', description: 'Уход, размеры, параметры' },
    ],
  },
  {
    id: 'stroitelstvo-i-remont',
    slug: 'stroitelstvo-i-remont',
    title: 'Строительство и Ремонт',
    description: 'Площади, объёмы, строительные материалы',
    subcategories: [
      { id: 'stroitelnye-materialy', slug: 'stroitelnye-materialy', title: 'Строительные материалы', description: 'Щебень, песок, кирпич, бетон' },
      { id: 'fundamenty', slug: 'fundamenty', title: 'Фундаменты', description: 'Расчёт фундаментов' },
      { id: 'otdelka', slug: 'otdelka', title: 'Отделка', description: 'Штукатурка, краска, обои' },
      { id: 'pokrytiya', slug: 'pokrytiya', title: 'Покрытия', description: 'Ламинат, линолеум, плитка' },
    ],
  },
  {
    id: 'transport',
    slug: 'transport',
    title: 'Транспорт',
    description: 'Расход топлива, стоимость поездки, налоги',
    subcategories: [
      { id: 'raskhod-topliva', slug: 'raskhod-topliva', title: 'Расход топлива', description: 'Расчёт расхода бензина и дизеля' },
      { id: 'stoimost-poezdki', slug: 'stoimost-poezdki', title: 'Стоимость поездки', description: 'Сколько стоит проезд' },
      { id: 'nalogi-i-sbory', slug: 'nalogi-i-sbory', title: 'Налоги и сборы', description: 'Транспортный налог, утильсбор' },
      { id: 'rastamozhka', slug: 'rastamozhka', title: 'Растаможка', description: 'Растаможка автомобилей' },
    ],
  },
  {
    id: 'tekhnologii',
    slug: 'tekhnologii',
    title: 'Технологии',
    description: 'Дата и время, генераторы, скорость интернета',
    subcategories: [
      { id: 'data-i-vremya', slug: 'data-i-vremya', title: 'Дата и время', description: 'Возраст, дни между датами, таймеры' },
      { id: 'generatory', slug: 'generatory', title: 'Генераторы', description: 'Пароли, числа, тексты' },
      { id: 'internet-i-fajly', slug: 'internet-i-fajly', title: 'Интернет и файлы', description: 'Скорость, размер файлов' },
      { id: 'tekhnologii-raznoe', slug: 'tekhnologii-raznoe', title: 'Разное', description: 'HTML редактор, калькулятор текста' },
    ],
  },
  {
    id: 'povsednevnoe',
    slug: 'povsednevnoe',
    title: 'Повседневное',
    description: 'Еда, размеры, питомцы, развлечения',
    subcategories: [
      { id: 'eda-i-napitki', slug: 'eda-i-napitki', title: 'Еда и напитки', description: 'Время варки, кулинарные меры' },
      { id: 'razmery', slug: 'razmery', title: 'Размеры', description: 'Одежда, обувь, кольца' },
      { id: 'pitomcy', slug: 'pitomcy', title: 'Питомцы', description: 'Возраст собак и кошек' },
      { id: 'razvlecheniya', slug: 'razvlecheniya', title: 'Развлечения', description: 'Зодиак, подбросить монетку' },
    ],
  },
];

export const categoryIcons: Record<string, string> = {
  'nauka-i-ucheba': 'Calculator',
  'konvertery': 'ArrowRightLeft',
  'procenty': 'Percent',
  'tajmery': 'Timer',
  'kulinarnye-mery': 'ChefHat',
  'zdorove-i-krasota': 'Heart',
  'stroitelstvo-i-remont': 'Home',
  'transport': 'Car',
  'tekhnologii': 'Cpu',
  'povsednevnoe': 'Coffee',
};
